# Generated by Django 4.0.2 on 2023-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='tests',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
